version: '2'
services:
  apache-apollo-data:
    build: ./apache-apollo
    image: sliw/apache-apollo:1.7.1
    volumes:
      - /opt/apollo-instance/data
      - /opt/apollo-instance/etc
      - /opt/apollo-instance/log
    entrypoint: /bin/true
  apache-apollo-instance:
    build: ./apache-apollo
    image: sliw/apache-apollo:1.7.1
    volumes_from:
      - apache-apollo-data
    ports:
      - "61613:61613"
      - "61680:61680"
  elasticsearch-data:
    build: ./elasticsearch
    image: sliw/elasticsearch:1.7.5
    volumes:
      - /usr/share/elasticsearch/config
      - /usr/share/elasticsearch/data
    entrypoint: /bin/true
  elasticsearch-instance:
    build: ./elasticsearch
    image: sliw/elasticsearch:1.7.5
    volumes_from:
      - elasticsearch-data
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana-instance:
    image: kibana:4.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch-instance:elasticsearch
    depends_on:
      - elasticsearch-instance
  webmanager-instance:
    build: ./sliwwebmanager
    image: sliw/webmanager:1.0
    ports:
      - "80:8080"
    links:
      - elasticsearch-instance:elasticsearch
    depends_on:
      - elasticsearch-instance
  server-instance:
    build: ./sliwserver
    image: sliw/server:1.0
    links:
      - elasticsearch-instance:elasticsearch
      - apache-apollo-instance:apache-apollo
    depends_on:
      - elasticsearch-instance
      - apache-apollo-instance